name: Kamus Bali FE CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Continous Integration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          working-directory: fe-test  
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build Push Image
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          content: fe-test
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/fe-test:latest
  deploy:
    runs-on: ubuntu-latest
    name: Continous Deployment
    needs: [docker-build]
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/fe-test
            docker compose -f docker-compose-fe-test.yml down &&
            docker compose -f docker-compose-fe-test.yml pull &&
            docker compose -f docker-compose-fe-test.yml up -d