name: Kamus Bali FE CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Continous Integration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: fe-test
        run: npm ci

      - name: Build Next.js
        working-directory: fe-test
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build Push Image
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # my dockerfile in the fe-test folder
          file: fe-test/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/kamus-bali-fe:latest

  deploy:
    runs-on: ubuntu-latest
    name: Continous Deployment
    needs: [docker-build]
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/fe-test
            docker compose -f docker-compose-fe-test.yml down &&
            docker compose -f docker-compose-fe-test.yml pull &&
            docker compose -f docker-compose-fe-test.yml up -d